name: onyx
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  talker_dio_logger: ^2.4.0
  dartz: any
  flutter_localizations:
    sdk: flutter
  intl:
  flutter_bloc: ^8.1.4
  get_it: any
  injectable: any
  flutter_screenutil:
  shared_preferences: ^2.2.2
  retrofit: ^4.1.0
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.0
  page_transition: ^2.1.0
  get_storage: ^2.1.1
  fluttertoast: ^8.2.4
  awesome_dio_interceptor: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  intl_utils: ^2.8.6
  flutter_gen_runner: ^5.2.0
  injectable_generator:
  build_runner: ^2.4.7
  retrofit_generator: ^8.1.0
  json_serializable: ^6.6.1
flutter_gen:
    output: lib/core/assets
    line_lenght: 160
    null_safety: true

    integrations:
      flutter_svg: true




flutter_intl:
    enabled: true
    main_locale: en
    output_dir: lib/core/generated
    arb_dir: lib/core/language

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
